### ISSUE TITLE
An error occurred (ValidationError) when calling the InvokeEndpoint operation: Endpoint xgboost-2020-02-08-multi is not a multi-model endpoint and does not support target model header.

### ISSUE THREAD

**Issue by warner121** [aws/amazon-sagemaker-examples#1026]
Hi There,

I'm having some issues specifying which model I want from my multi-model endpoint. I created my endpoint configuration as follows:

```
endpoint_config_name = 'xgboost-2020-02-08-multi'
endpoint_config_response = sagemaker.create_endpoint_config(
    EndpointConfigName = endpoint_config_name,
    ProductionVariants=[
        {
        'InstanceType':'ml.t2.medium',
        'InitialInstanceCount':1,
        'ModelName':'xgboost-2020-02-08-11-45-57-071',
        'VariantName':'Model-A',
        'InitialVariantWeight':1
        },
        {
        'InstanceType':'ml.t2.medium',
        'InitialInstanceCount':1,
        'ModelName':'xgboost-2020-02-08-12-00-44-826',
        'VariantName':'Model-B',
        'InitialVariantWeight':1
        }
    ])
```

And the endpoint like so:

```
endpoint_name = 'xgboost-2020-02-08-multi'
endpoint_params = {
    'EndpointName': endpoint_name,
    'EndpointConfigName': endpoint_config_name,
}
endpoint_response = sagemaker.create_endpoint(**endpoint_params)
```

Now, the endpoint works nicely in distributing requests evenly between my 2 models:

```
sagemaker = boto3.client('runtime.sagemaker', region_name='eu-west-2')
response = sagemaker.invoke_endpoint(EndpointName='xgboost-2020-02-08-multi',
                                     ContentType='text/csv',
                                     Body=payload)
```

Returns a valid response with the randomly selected model indicated in the headers. However , specifying the TargetModel parameter generates the error in the title.

```
response = sagemaker.invoke_endpoint(EndpointName='xgboost-2020-02-08-multi',
                                     ContentType='text/csv',
                                     Body=payload, 
                                     TargetModel='xgboost-2020-02-08-11-45-57-071')
```

Can anyone please indicate what I am doing wrong? This error makes no sense to me as in the first case it is clearly functional as a multi-model endpoint.

**Comment by ajhoekst** [comment]
I am experiencing the same issue. Did you find resolution?

**Comment by tayyabayounas** [comment]
I am having the same issue. Did anybody resolve it?

**Comment by yosun** [comment]
Yes likewise after a SDK update...

**Comment by pradeep-bhadauria** [comment]
Did anyone found the solution yet? Facing same issue.

**Comment by JoshuaFox** [comment]
I am also hitting this. Solutions?

**Comment by jkroll-aws** [comment]
Try specifying the model filename for the TargetModel rather than the model name. See the documentation on [Invoke a Multi-Model Endpoint](https://docs.aws.amazon.com/sagemaker/latest/dg/invoke-multi-model-endpoint.html), as well as several example notebooks on multi-model endpoints using [Linear Learner](https://github.com/aws/amazon-sagemaker-examples/blob/master/advanced_functionality/multi_model_linear_learner_home_value/linear_learner_multi_model_endpoint_inf_pipeline.ipynb), [SKLearn](https://github.com/aws/amazon-sagemaker-examples/blob/master/advanced_functionality/multi_model_sklearn_home_value/sklearn_multi_model_endpoint_home_value.ipynb), and [Bring Your Own Algorithm Container](https://github.com/aws/amazon-sagemaker-examples/blob/master/advanced_functionality/multi_model_bring_your_own/multi_model_endpoint_bring_your_own.ipynb).

**Comment by JoshuaFox** [comment]
Thank you.  Using the filename, as here, gives the same error message
```
response = client.invoke_endpoint(EndpointName=endpoint_name, TargetModel="model.tar.gz", ContentType="text/x-libsvm",  Body=payload)
```

Sagemaker has to find this file, and per[ that Notebook](https://github.com/aws/amazon-sagemaker-examples/blob/master/advanced_functionality/multi_model_bring_your_own/multi_model_endpoint_bring_your_own.ipynb) (the only one that uses filename for that),  "The TargetModel field is concatenated with the S3 prefix specified in ModelDataUrl when creating the model, to generate the location of the model in S3." Yet in my case `ModelDataUrl`, taken from `client.describe_training_job(TrainingJobName=job_name)["ModelArtifacts"]["S3ModelArtifacts"]` and used to deploy the model, is a full path  to the model, not the prefix, and so concatenating `model.tar.gz` to it does not make sense.

In any case, the error occurs in the same way. What might be the problem? Or is there more detailed documentation on this?

**Comment by JoshuaFox** [comment]
Thank you. That's it. 

I found [this to be the best example](https://github.com/aws/amazon-sagemaker-examples/blob/master/advanced_functionality/multi_model_xgboost_home_value/xgboost_multi_model_endpoint_home_value.ipynb). (Some of the others don't work because of obsolete libraries or do not use the relevant API).

See the last part  of that Notebook, in which `invoke_endpoint` is used (rather than a predictor).

It would be  good to get better documentation. For example only in this [Notebook](https://github.com/aws/amazon-sagemaker-examples/blob/master/advanced_functionality/multi_model_bring_your_own/multi_model_endpoint_bring_your_own.ipynb) did I find the statement 

> When creating the Model entity for multi-model endpoints, the container's ModelDataUrl is the S3 prefix where the model
>  artifacts that are invokable by the endpoint are located. The rest of the S3 path will be specified when invoking the model.

This should be in [the documentation](https://docs.aws.amazon.com/sagemaker/latest/dg/invoke-multi-model-endpoint.html), and it would be good to further clarify whether `ModelDataUrl` is meant to be a prefix onto which `model_filename.tar.gz` is appended (as above) or whether it is a full path to a file (as appears to be the case in some Notebooks).

**Comment by ngluna** [comment]
In [Create a Multi-Model Endpoint](https://docs.aws.amazon.com/sagemaker/latest/dg/create-multi-model-endpoint.html#create-multi-model-endpoint-sdk) in the SageMaker Dev Guide there is a line about: 

> "You also need to pass the ModelDataUrl field that specifies the prefix in Amazon S3 where the model artifacts are located, instead of the path to a single model artifact, as you would when deploying a single model."

But the [API Reference Guide](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_ContainerDefinition.html#sagemaker-Type-ContainerDefinition-ModelDataUrl) can be confusing:

> ModelDataUrl
> The S3 path where the model artifacts, which result from model training, are stored. This path must point to a single gzip compressed tar archive (.tar.gz suffix). 

I've contacted an engineer on the MME team to for clarification.

**Comment by jkroll-aws** [comment]
Closing since we have identified a solution.
