### ISSUE TITLE
/bin/sh: 1: docker: not found

### ISSUE THREAD

**Issue by sportsapril** [aws/amazon-sagemaker-examples#1259]
When I tried following some fo the examples to build my own container, I constantly ran into this problem. How to resolve this?

**Comment by sugarcrm-aorso** [comment]
@sportsapril Was seeing something similar. If you are trying to use SageMaker Studio, it doesn't look like Docker is installed by default on those notebook instances. It is installed on the non-Studio notebook instances though so I'd try there first to see if it works.

**Comment by IvyBazan** [comment]
@sportsapril Are you running these notebooks from SageMaker Studio or a SageMaker Notebook instance?

**Comment by seanpmorgan** [comment]
As mentioned this is likely because of SageMaker Studio limitations. The current work around is to use a pip installable package `sagemaker-studio-image-build` as shown in this blog:
https://aws.amazon.com/blogs/machine-learning/using-the-amazon-sagemaker-studio-image-build-cli-to-build-container-images-from-your-studio-notebooks/

Alternatively you can push the image to ECR using aws cli and then just pick up the URI in your Studio notebook. This painpoint is acknowledge and in the future there may be a better solution.

Closing due to lack of response.
