### ISSUE TITLE
Unable to train model on p2.xlarge instance

### ISSUE THREAD

**Issue by shubhamsharma1609** [aws/amazon-sagemaker-examples#1425]
I am using conda_tensorflow_p36 kernel on a ml.p2.xlarge  instance. When I am training on 150 images and resizing each image to 2000*2000 pixels, the kernel dies. Whereas when I resize each image for training into 512 *512 pixels,I am getting resource exhausted error.I am using keras .Please guide as to what can be done.

```
ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[30,512,512,16] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node dropout_9/cond/dropout/random_uniform/RandomUniform}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[loss/mul/_1021]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[30,512,512,16] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node dropout_9/cond/dropout/random_uniform/RandomUniform}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.

```

**Comment by seanpmorgan** [comment]
Hi @shubhamsharma1609 this is an issue related to TensorFlow/Keras and memory allocation which would be better brought up on TensorFlow stack overflow. Typically this occurs because your trying to predict on a batch larger than available GPU memory. My advice would be try a small (even single image for debugging) batch size.

However, because this is not related to any examples in this repository I'm going to close the issue. If it is related to an example please let us know and we can re-open. Thanks!
