### ISSUE TITLE
pytorch_torchvision_neo.ipynb: Compilation Job not optimizing the Model 

### ISSUE THREAD

**Issue by CloudaYolla** [aws/amazon-sagemaker-examples#1776]
Tested the NB in SageMaker Studio and got the following errors

NB: https://github.com/aws/amazon-sagemaker-examples/blob/master/sagemaker_neo_compilation_jobs/pytorch_torchvision/pytorch_torchvision_neo.ipynb

## Issue

The model size is: 41 MB
After the compilation job, the model size becomes 81 MB, which conflicts with the Neo proposition. Please either update the code to optimize the model size, or make other benefits clear to the reader (is it performance, cost etc?)

**Comment by samskalicky** [comment]
Hi @CloudaYolla, 

The claim that Neo makes things smaller is mainly for Edge devices rather than compilation for cloud (ie. SageMaker). Besides, the claim mainly revolves around the size of the total installation of tools/frameworks (ie. for compiled models you wouldnt need to install PyTorch to run a compiled model on edge) so the overall footprint would be smaller. 

But at the end of the day Neo isnt doing any model pruning, so the size of the model binaries should be similar (most model sizes are driven by the size of the weights). And for cloud targets the file size on disk is not as much of an issue as the size of the model in memory.
