### ISSUE TITLE
Fail to install Shap because of missing gcc on SageMaker Studio

### ISSUE THREAD

**Issue by stechr** [aws/amazon-sagemaker-examples#1890]
Hi,

I'm running /amazon-sagemaker-examples/autopilot/model-explainability/explaining_customer_churn_model.ipynb  in SageMaker Studio.  
Installing Shap with` !python -m pip install shap` fails because of missing gcc:
`gcc -pthread -B /opt/conda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/opt/conda/include/python3.7m -I/opt/conda/lib/python3.7/site-packages/numpy/core/include -c shap/_cext.cc -o build/temp.linux-x86_64-3.7/shap/_cext.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /opt/conda/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xt6ic0x5/shap/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xt6ic0x5/shap/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-fglb2x_l/install-record.txt --single-version-externally-managed --compile --install-headers /opt/conda/include/python3.7m/shap Check the logs for full command output.`

Installing SHAP with `conda install -c conda-forge shap` works fine and the entire notebook runs smoothly for me.

**Comment by seanpmorgan** [comment]
Hi @stechr, 

Installing with conda is recommended since it ships precompiled binaries. However if you didn't want to do that for some reason, you do have control over your underlying system installations in SM Studio. If you run:
```
!apt-get update && apt-get install -y build-essential
!python -m pip install shap
```
It runs successfully.


If there are a lot of changes you'd like to make to your studio then it's likely a good usecase for bringing your own sagemaker studio image:
https://docs.aws.amazon.com/sagemaker/latest/dg/studio-byoi.html

**Comment by seanpmorgan** [comment]
Re-opening this until the notebook get's fixed.

**Comment by stechr** [comment]
Created PR https://github.com/aws/amazon-sagemaker-examples/pull/1934
