### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by Previatto** [aws/amazon-sagemaker-examples#1917]
Should be "setup"

https://github.com/aws/amazon-sagemaker-examples/blob/535a834ed2e6015341a6cd91de864a43f3bad14e/reinforcement_learning/rl_cartpole_batch_coach/rl_cartpole_batch_coach.ipynb#L59

**Comment by seanpmorgan** [comment]
Hi @Previatto would you like to submit a pull request to fix this?

**Comment by Previatto** [comment]
Hello Sean, I see that TeeVen already did that, still can you point me to a documentation on how to do these pull requests?

**Comment by seanpmorgan** [comment]
Hi @Previatto so typically I would point you to a guide on forking repos and submitting pull requests. This is a great example:
https://github.com/gabrieldemarmiesse/getting_started_open_source

But for something as small as a typo, the GitHub webpage now makes this quite easy. Goto the file you'd like to change and select the "edit" pencil. Make your changes and at the bottom it'll ask you to fork and create pull request. Simply select that and your done!

Thanks for reporting. Closing since this is fixed.
