### ISSUE TITLE
What is the range of rotation angle in lidar?

### ISSUE THREAD

**Issue by mariya12290** [aws/amazon-sagemaker-examples#1949]
Hey @TEChopra1000

I am labeling lidar point cloud for object detection. I am following the kitti labeling format. So I just need to know what is the range of rotation angle around Z axis in lidar?
Is it between (-pi, pi) as in kitti? 
Please let me know

Thanks in advance

**Comment by TEChopra1000** [comment]
@mariya12290 
The yaw measurement in the output data is 180 degrees, or pi in radians, minus yaw in the right handed world coordinate system when looking down at the cuboid. In other words, when looking at a cuboid from the top-down, `yaw_in_output_data` is clockwise-positive (in contrast to the right handed world coordinate system, in which the top-down view is associated with counter-clockwise positive rotation). When looking up from the cuboid, `yaw_in_output_data` is counterclockwise-positive.
Take a look here for more details and please let me know if you have any follow up questions. 
https://docs.aws.amazon.com/sagemaker/latest/dg/sms-data-output.html#sms-output-point-cloud-object-detection

**Comment by TEChopra1000** [comment]
Additionally, GT does not have hard limit on yaw’s range. The annotation UI can handle value out of the range (-pi, pi). For example, if the worker put -270 degrees as yaw, the cuboid has the same direction as 90 degree or 450 degree. With the output GT doesn't do any range conversion either, just coverts the unit from degree to radian.

**Comment by Suri12990** [comment]
@TEChopra1000  Thank you so much for the explanation.  
But still I do not understand why I need to minus yaw from pi to get the orientation in right hand coordinate system(RHCS). My understanding of RHCS is, x facing front, y facing left and Z facing up. Since the lidar(in my case) co-ordinate system is already in RHCS. why I need to minus the yaw from pi to get the yaw in RHCS?. It is bit confusing. 

When I feed the data into labeling tool, I am not doing  either transformation into world co-ordinate system(WCS) or to camera co-ordinate system(CCS). I am keeping the data in the lidar co-ordinate system which is already in RHCS.  The reason is my labeling range is not too big, so I can label the objects properly which are nearer. 

Please correct me If I am wrong, according to aws documentation, it is recommended to keep both camera and lidar data in WCS or same co-ordinate system. If the Lidar data points are in camera co-ordinates system, I get the rotation around y-axis(around pitch) in camera co-ordinates system(x facing side, Y facing down and z facing front)!. So in order to get the rotation around yaw in lidar coordinate system(LCS), do we do yaw_output_rhcs = pi - yaw_output! 
Because in kitti data set, 3D bounding box rotation is in CCS, which means rotation around y -axis, in order to get into rotation around z in LCS, people usually do  rot_z = -rot_y - pi/2. 

looking for the positive response

**Comment by mariya12290** [comment]
@TEChopra1000  Thank you so much for the explanation.  
But still I do not understand why I need to minus yaw from pi to get the rotation in right hand coordinate system(RHCS). My understanding of RHCS is, x facing front, y facing left and Z facing up. Since the lidar(in my case) co-ordinate system is already in RHCS. why I need to minus the yaw from pi to get the yaw in RHCS?. It is bit confusing. 

When I feed the data into labeling tool, I am neither transforming into world co-ordinate system(WCS) nor to camera co-ordinate system(CCS). I am keeping the data in the lidar co-ordinate system which is already in RHCS.  The reason is my labeling range is not too big, so I can label the objects properly which are nearer. 

Please correct me If I am wrong, according to aws documentation, it is recommended to keep both camera and lidar data in WCS or same co-ordinate system. If the Lidar data points are in camera co-ordinates system, I get the rotation around y-axis(around pitch) in camera co-ordinates system(x facing side, Y facing down and z facing front)!. So in order to get the rotation around yaw in lidar coordinate system(LCS), do we do yaw_output_rhcs = pi - yaw_output? Did the tool assume itslef, lidar points are in WCS or CCS, not in LCS. is that the reason for subcontracting yaw_output?

Because in kitti data set, 3D bounding box rotation is in CCS, which means rotation around y -axis, in order to get the rotation around z in LCS, people usually do  rot_z = -rot_y - pi/2. 

looking for the positive response

**Comment by TEChopra1000** [comment]
The Ground Truth annotation tool internally applies `PI - yaw_rhcs` which is the yaw value you see from annotation UI and the value we output in manifest. So if you want to get the original right handed yaw, you will need to apply `PI - yaw`, which will be `PI - (PI - yaw_rhcs) = yaw_rhcs`. This specific translation should only be applied to cuboid label, not the LiDAR nor camera levels. Both LiDAR and camera use Quaternion to represent orientation, which can help avoid such confusion.

We do recommend to use world-coordinate system or same local coordinate system. Lidar’s local coordinate system is best if you want to use LCS, since the annotation tool will put z-axis in the vertical direction. If you covert point cloud data into camera’s coordinate system and used CCS as the same local coordinate system, since Camera’s z-axis is forward direction, the rendered point cloud view may look weird.

For example, if you already have cuboid labels created from other platform (assume the other platform create cuboid by following the right handed rule), and you want to load those audit those labels in GroundTruth using a verification job, you will need to apply `PI - yaw_rhcs` before loading cuboid labels to GroundTruth. Here the `yaw_rhcs = rot_z = -rot_y - pi/2`. This is the case if want to load Kitti data into GroundTruth

**Comment by Suri12990** [comment]
@TEChopra1000  Thank you so much for the explanation

**Comment by mariya12290** [comment]
@TEChopra1000  Thank you so much for the explanation
