### ISSUE TITLE
Instance support for built-in algorithms

### ISSUE THREAD

**Issue by sbhavani** [aws/amazon-sagemaker-examples#1951]
While working through this example on SageMaker Studio: https://github.com/aws/amazon-sagemaker-examples/blob/master/sagemaker_neo_compilation_jobs/tensorflow_distributed_mnist/tensorflow_distributed_mnist_neo.ipynb

I received the following error:
```ClientError: An error occurred (ValidationException) when calling the CreateTrainingJob operation: Instance type ml.c4.2xlarge is not supported by algorithm image-classification; only GPU instances are supported.```

Is there any reason that we can't use CPU instances? Many data scientists may be okay with long-running training jobs especially during the experimentation phase.

**Comment by seanpmorgan** [comment]
Hi @sbhavani per the documentation:
```
For image classification, we support the following GPU instances for training: ml.p2.xlarge, ml.p2.8xlarge, ml.p2.16xlarge, ml.p3.2xlarge, ml.p3.8xlargeand ml.p3.16xlarge.
```
https://docs.aws.amazon.com/sagemaker/latest/dg/image-classification.html

The algorithm is designed to train efficiently so while GPU instances may cost more they should train more efficiently from a cost stand point. During inference you can use CPU instances for this algorithm.

Closing because this is not related to any specific SageMaker example. The linked example notebook runs a TensorFlow estimator on an MNIST script; not the built in image-classification SM algo.
