### ISSUE TITLE
Hosting spacy models using sagemaker with endpoint

### ISSUE THREAD

**Issue by chinnusujitha** [aws/amazon-sagemaker-examples#1956]
I'm new to sagemaker, My requirement is i have spacy model(where there is no training required),Now i want to deploy the model using sagemaker with endpoint, so that i can use that endpoint in my project. I'm following this link, but i didn't figure out on how to use this model as an endpoint. Can someone help me in getting this done.

**Comment by seanpmorgan** [comment]
Hi @chinnusujitha which link are you referring to? I found this medium post which specifically talks about deploying spacy models:
https://medium.com/analytics-vidhya/how-to-run-spacy-on-aws-sagemaker-custom-containers-quick-and-easy-884a6898ed48

This is not content from our team though so we can not provide support on that. Here is some documentation on how to host pretrained models in custom containers on sagemaker though:
https://docs.aws.amazon.com/sagemaker/latest/dg/your-algorithms-inference-code.html

This repo may be of use because they're doing a custom model deployment (for Keras not spacy):
https://github.com/aws-samples/amazon-sagemaker-keras-text-classification/tree/master/container/sagemaker_keras_text_classification

Just a note to those who read this... there is no need to use a custom container for Keras models. You can use the TensorFlow Estimator/Model deploy paradigm.

**Comment by chinnusujitha** [comment]
Hi @seanpmorgan , I have gone through that medium link, here my question is i don't have model artifacts/checkpoints, i'm using predefined package something like spacy, now i want to deploy this using sagemaker with endpoint, so that i can use that endpoint in my application. Can you help me on this.

**Comment by seanpmorgan** [comment]
Hi @chinnusujitha so spacy should be able to serialize models. You can upload the binary to s3 and load it in a custom docker container for inference as per the custom algo deployment links above:
https://spacy.io/usage/saving-loading

**Comment by hsl89** [comment]
Hi @chinnusujitha , please post the question here https://stackoverflow.com/questions/tagged/amazon-sagemaker
