### ISSUE TITLE
[Bug Report] SAC algorithm file missing in reinforcement_learning/deepracer 

### ISSUE THREAD

**Issue by Currycurrycurry** [aws/amazon-sagemaker-examples#2126]
I have only found the  PPO algorithm but the other SAC is not found. It would bew greatly helpful if anyone can upload the corresponding SAC training file😭

**Comment by Currycurrycurry** [comment]
@djarpin @mvsusp ping

**Comment by yunzhe-tao** [comment]
Hi @Currycurrycurry, we will let you know once we updated the notebook to add those features. Thanks!

**Comment by yunzhe-tao** [comment]
Hi @Currycurrycurry, we have updated the notebook. Now SAC is enabled but we do not have an available SAC template yet. In order to try SAC by yourself, you can edit the model metadata file, and add `"training_algorithm": "clipped_ppo"` to the metadata. For hyper-parameters, you can refer to the default ones in Coach.

**Comment by nevakrien** [comment]
hey the notebook is just not there now
