### ISSUE TITLE
PyTorch Studio Notebook, GPU optimized, too slow

### ISSUE THREAD

**Issue by HabibAouani** [aws/amazon-sagemaker-examples#2160]
**Describe the bug**
My PyTorch training doesn't run on GPU, and I don't know why. Even if I'm running it in GPU optimized for PyTorch instance, and even if I'm sending all my tensors/model/Criterion to('cuda).
I'm using PyTorch 1.6 Python 3.6 GPU optimized kernel, in Sagemaker Studio. (Running PyTorch on a Docker image)

**To Reproduce**
Launch the instance PyTorch optimized for GPU, in Sagemaker Studio.
Run a simple classification on images.
Training doesn't run on GPU, only on CPU, which is making it too slow. I cannot figure out why.

Please help, as I'm on a critical path on my project.
Thank you very much,
Habib

**Comment by HabibAouani** [comment]
After some testing, it seems that it's not consuming any of the GPU inplace. Tensorflow does, which is confusing. The command nvidia-smi shoes no process running, even if I'm sending everything to cuda().
![image](https://user-images.githubusercontent.com/29917008/115996925-89059080-a5e1-11eb-9d19-96364e0d1d2f.png)

**Comment by aaronmarkham** [comment]
In Studio, your training jobs don't run locally. They'll run on another instance that is created for your training job. This is probably why you don't see anything when you run nvidia-smi. If you want to use code that uses "local mode", you can use a Notebook Instance instead of Studio.

Please check on the forums for help. You'll likely get a faster response. If you post about a specific example that isn't running in Studio that is intended for Studio, please post the link to the example, and reopen this issue.
