### ISSUE TITLE
Pandas version not matching

### ISSUE THREAD

**Issue by anuraagrijal3138** [aws/amazon-sagemaker-examples#398]
I upgraded to latest version of Pandas from pip.

But in my notebook instance when I use "pd.show_versions(as_json=False)" it shows 
pandas: 0.22.0
but I need version 0.23.0 to use pd.get_dummies() to set the dtype

**Comment by djarpin** [comment]
Hi @anuraagrijal3138 - How did you upgrade your version of Pandas?  Since we're using conda environments, it possible that your pip install didn't take effect on the environment your notebook is using.  See the [SageMaker documentation](https://docs.aws.amazon.com/sagemaker/latest/dg/nbi-add-external.html) for more details on installing packages.  Thanks.

**Comment by seanpmorgan** [comment]
Closing as this appears to be not related to anything specific in this repo. Please let us know if you still need assistance.
