### ISSUE TITLE
Converting AWS SageMaker Model to TensorFlow

### ISSUE THREAD

**Issue by mkhizeryounas** [aws/amazon-sagemaker-examples#580]
Hi, I created a training job for factorisation machine and made a model. Now I want to use the model in my mobile projects i.e. converting them into tensorflow lite. Is there a way that I can convert sagemaker model to tensorflow and then tensorflow lite?

**Comment by collinp-spindance** [comment]
@mkhizeryounas If you do find a solution, please let me know. I am hoping to do the same thing.

**Comment by csmcallister** [comment]
I'm also wanting to do this and will post back if research uncovers anything.

In the meantime, I suspect this functionality isn't baked into SageMaker so one would have to use the [converter ](https://www.tensorflow.org/lite/guide/get_started#tensorflow_lite_converter)on a saved tensorflow model. Since SageMaker dumps models to s3, a lambda function could contain this converter and, using the s3 bucket as an event source, convert every normal tensorflow model that is created via SageMaker. You just need to be sure that your original model is [compatible](https://www.tensorflow.org/lite/guide/ops_compatibility).

**Comment by hsl89** [comment]
https://stackoverflow.com/questions/tagged/amazon-sagemaker

**Comment by SriniVest** [comment]
How about Sagemaker Neo
