### ISSUE TITLE
EIA deploy error no libcuda.so.1

### ISSUE THREAD

**Issue by austinmw** [aws/amazon-sagemaker-examples#613]
I'm trying to deploy a TF Script Mode trained model that uses TF Serving to a CPU+EIA, but the endpoint is failing to be created. The logs say:

> tensorflow_model_server: error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory

So does TF Serving require CUDA Toolkit? and If so is this toolkit not installed on SM official cpu/eia docker images?

**Edit:** Actually this now seems like a duplicate of a previous bug I posted. Working backwards, the model created from estimator.deploy lists the image pulled as the GPU version: `520713654638.dkr.ecr.us-west-2.amazonaws.com/sagemaker-tensorflow-serving:1.12.0-gpu` even though I specified a cpu instance type.

**Comment by ChoiByungWook** [comment]
Hello @austinmw,

Sorry for the late response.

Can you post your Python SDK code that you use to run your SageMaker job?

If I understand you correctly, it seems the EI CPU image is failing out with the error message `libcuda.so.1:' above or the GPU image is actually being pulled down instead of the EI image.

I apologize for the inconvenience.

**Comment by austinmw** [comment]
If I do: 

```
train_instance_type =  'ml.p3.2xlarge'

estimator = TensorFlow(entry_point='launcher.sh',
                       source_dir='src',
                       train_instance_type=train_instance_type,
                       train_instance_count=1,
                       hyperparameters=hyperparameters,
                       role=role,
                       framework_version='1.12',
                       py_version='py3', 
                       script_mode=True,
                       output_path=output_path,
                       dependencies=[],
                       metric_definitions=metric_definitions)

estimator.fit(inputs)

predictor =  deploy(initial_instance_count=1,
                                 instance_type='ml.c5.xlarge', 
                                 accelerator_type='ml.eia1.large')
```

Deploying fails with that error. Checking the image it pulled under console shows the gpu version. I have to do this instead:

```
    model = Model(model_data=estimator.model_data,
                  role=sagemaker.get_execution_role(),
                  image=None,
                  framework_version='1.12')

    predictor = model.deploy(endpoint_name=endpoint_name,
                                  initial_instance_count=1,
                                  instance_type='ml.c5.xlarge',
                                  accelerator_type='ml.eia1.large')
```

**Comment by ChoiByungWook** [comment]
@austinmw,

Are you running in a Jupyter notebook?

What version of the Python SDK are you using?

I'm having some trouble reproducing this. I debugged this with pdb and I am getting proper CPU images back.

**Comment by ChoiByungWook** [comment]
I tried reproducing this with this notebook: https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/tensorflow_iris_dnn_classifier_using_estimators/tensorflow_iris_dnn_classifier_using_estimators_elastic_inference.ipynb

I replaced the instance type to ml.p3.2xlarge for the training instance and passed in a ml.c5.xlarge for the deploy.

I checked the training-job and it pulled the gpu image and also checked the model and endpoint. The correct image was pulled for both. Attaching my images.

Training job details
<img width="733" alt="training_cifar_notebook" src="https://user-images.githubusercontent.com/12059958/52840231-76ac7580-30ad-11e9-878c-5c9e516e740a.png">

SageMaker Model attached to my endpoint
<img width="467" alt="model_attached_to_myendpoint" src="https://user-images.githubusercontent.com/12059958/52840240-7e6c1a00-30ad-11e9-96dd-29eb1b4661fe.png">

**Comment by ChoiByungWook** [comment]
@austinmw,

I believe I found the root cause now.

The script_mode flag being True ends up with the base Model object being created instead of the TensorFlowModel object, which leads to the proper construction of the ECR image.

https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/tensorflow/estimator.py#L407

This leads to this code being called that generates the GPU ECR image you saw pointing to the [tensorflow-serving-container](https://github.com/aws/sagemaker-tensorflow-serving-container).

https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/tensorflow/serving.py#L125

I don't think this is the proper user experience we should be giving at all and I apologize for that. Let me relay this back to the team and try to get a resolution.

Thank you for reporting this.

**Comment by austinmw** [comment]
@ChoiByungWook sorry for the late reply. Awesome that you were able to track down the issue, thanks!

**Comment by ChoiByungWook** [comment]
For reference: 

https://github.com/awslabs/amazon-sagemaker-examples/issues/609
https://stackoverflow.com/questions/54485769/sagemaker-deploying-to-eia-from-tf-script-mode-python3

**Comment by austinmw** [comment]
Added an edit that I needed to use `sagemaker.tensorflow.serving.Model` instead of `sagemaker.tensorflow.TensorFlowModel`

**Comment by ChoiByungWook** [comment]
For reference: https://github.com/aws/sagemaker-python-sdk/commit/4732545bd9d1880390b3951c9b941f2bb62d6e5a#r32336726
