### ISSUE TITLE
Issue when running container in another machine

### ISSUE THREAD

**Issue by LakshKD** [aws/amazon-sagemaker-examples#655]
I have tried running the container present at https://github.com/awslabs/amazon-sagemaker-examples/tree/master/advanced_functionality/scikit_bring_your_own/container on my machine having MacOS and it ran successfully but when I tried running it on another machine having the same MacOS then it is properly starting the inference server but when calling the predict.sh script with the Test Data it is throwing the following error: 

ImportError: libopenblasp-r0-382c8f3a.3.5.dev.so: cannot open shared object file: No such file or directory

I searched over the internet and figured out this error relates to some numpy issue, so can anybody please help me out that how to resolve it, do we need to change the numpy version inside DockerFile or do we need to do anything, just tell me I can raise a PR too if anything needs to be changed in DockerFile.

**Comment by LakshKD** [comment]
One more thing which I want to mention is that the DockerFile present in the above mentioned directory now contains the numpy version == 1.16.2. But earlier it was numpy==1.15.0, Is the above problem came because of that ?

**Comment by seanpmorgan** [comment]
Hi @LakshKD apologies for the slow response. This looks to be related to your OS and loading a specific SO file. Likely it's related to this numpy issue:
https://github.com/numpy/numpy/issues/8076

It's tough to no exactly how to fix it since its specific to your machine. I would recommend installing numpy with conda though since it comes with a specific version of gcc to load python extensions. Inside of the Docker container there should not be an issue. Recently tested the upgraded container.

Closing as this is quite old but let us know if you're still having issue.
