### ISSUE TITLE
[Question] Batch transformer with images for object detection task

### ISSUE THREAD

**Issue by Andreachen0707** [aws/amazon-sagemaker-examples#918]
Hi,
Not sure if this is a correct place to ask, but if there would be any help it is grateful. 
I'm using sagemaker batch transform job for object detection task using my own model. I test multiple combinations of parameters(MaxConcurrentTrans, MaxPayload, instance_count) in order to have a good understanding of how long the job would take.
Below is the result I got (on ~500 images each size around 200kb):

| Instance_type | payload | concurrent_trans | instance_count | duration/min |
| ----------- | ----------- | ----------- | ----------- | ----------- |
| ml.p2.xlarge(GPU) | 2 | 6 | 1 | 19|
| ml.p2.xlarge(GPU) | 6 | 1 | 1 | 22|
| ml.p2.xlarge(GPU) | 2 | 1 | 2 | ***75***|
| ml.c5.2xlarge(CPU) | 6 | 3 | 1| 65|
| ml.c5.2xlarge(CPU) | 6 | 1 | 1| 40|
| ml.c5.2xlarge(CPU) | 6 | 1 | 3| 27|
| ml.c5.2xlarge(CPU) | 6 | 2 | 3| 25|

So here is the part I don't understand: in my understanding, multiple instances means distributing objects to different instances. For example, the time of doing inference with 3 instances should be one third the time of doing it with 1 instance. Also, increase the number of concurrent trans should also increase the speed.
From the table above though, it is not the case. I'm wondering, is there a way to better determine what is the best set of parameters for doing large batch transform job?

Thanks in advance!

**Comment by Aloha106** [comment]
Hi, thanks for using SageMaker. 
1. Since the input is image, which is sent to the algorithm one by one, the payload size doesn't matter as long as it's larger than the size of the image. The payload size is used to determine how many records to include in each request sent to the algorithm when the record is splittable, e.g. CSV lines, JSONLines.
2. the max_concurrent_transform means the max concurrent requests Batch will send to the algorithm container but doesn't mean the actual max concurrent request the model can handle. The actual max concurrency reached is determined by multiple factors, e.g. the algorithm and the number of cores on the instances. For example, p2.xlarge only have one GPU (https://aws.amazon.com/ec2/instance-types/p2/), so larger concurrency may not be achievable by the algo.
3. For instance count, yes, we'll distribute the input to different instances. So theoretically the transform time should be less when increasing the instance count. Could you confirm how the duration is measured? It should be the time used in transformation (TransformEndTime - TransformStartTime ), not the total job duration.

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team
